import { Inter } from "next/font/google";
import "./globals.css";
// import { QueryProvider } from "../providers/react-query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-amber-700`}>
        {/* <header>header</header> */}
        {children}
        {/* <footer>footer</footer> */}
        {/* <QueryProvider></QueryProvider> */}
      </body>
    </html>
  );
}
